### ISSUE TITLE
Domain

### ISSUE THREAD

**Issue by ICS-Vortex** [mobizel/markdown-docs-bundle#126]
How to change a domain of the base route? 
When I try to add host option in YAML config file - my entire application fails with 500

**Comment by ICS-Vortex** [comment]
Found solution. 
Inside config/routes/mobizel_markdown
```
_mobizel_markdowns:
  resource: 'mobizel_markdown_docs.routing.context_loader'
  type: service
  host: '%docsHost%'
```

**Comment by ICS-Vortex** [comment]
Found solution. 
Inside config/routes/mobizel_markdown
```
_mobizel_markdowns:
  resource: 'mobizel_markdown_docs.routing.context_loader'
  type: service
  host: '%docsHost%'
```
