### ISSUE TITLE
Localization feature

### ISSUE THREAD

**Issue by wtty** [mobizel/markdown-docs-bundle#80]
A way to translate documents would be nice, maybe separating docs with locale directories?

Sample structure:

```
docs
    en
        - index.md
    fr
        - index.md
```

**Comment by loic425** [comment]
I've just tried that and it works fine.

```yaml
mobizel_markdown_docs:
    contexts:
        main:
            path: /docs/{locale}
            docs_dir: '%kernel.project_dir%/docs/{locale}'
            requirements:
                locale: '[a-z]+'
```

![locale_en](https://user-images.githubusercontent.com/8329789/117799714-b0e82b80-b252-11eb-9140-e489b0f077bb.png)
![locale_fr](https://user-images.githubusercontent.com/8329789/117799718-b2195880-b252-11eb-8888-60a5b2fd9f8c.png)
